name: .NET Test

on:
  push:
    branches:
      - main
      - 'develop/**'
    paths:
      - '**.cs'
      - '**.yml'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Show CalculatorTest.cs contents
        run: type MyTest\CalculatorTest.cs
        working-directory: ./MyConsoleApp

      - name: Setup .NET 5.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '5.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./MyConsoleApp

      - name: Build
        run: dotnet build --no-restore
        working-directory: ./MyConsoleApp

      - name: Test
        run: dotnet test --no-build --logger "trx;LogFileName=test-results.trx"
        working-directory: ./MyConsoleApp

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool
      
      - name: Add .dotnet/tools to PATH
        run: echo "$env:USERPROFILE\.dotnet\tools" | Out-File -Append $env:GITHUB_PATH     

      - name: Check for .trx file
        run: dir .
        working-directory: ./MyConsoleApp

      - name: Check for .trx file
        run: dir .
        working-directory: ./MyConsoleApp/MyTest

      - name: Generate HTML report
        run: reportgenerator -reports:"MyConsoleApp/TestResults/test-results.trx" -targetdir:"MyConsoleApp/TestResults/html" -reporttypes:Html
      
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: test-report-html
          path: ./MyConsoleApp/TestResults/html
