name: .NET Test

on:
  push:
    branches:
      - main
      - 'develop/**'
    paths:
      - '**.cs'
      - '**.yml'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 5.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '5.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --logger "trx;LogFileName=test-results.trx"
